name: Movies
options:
  bundleIdPrefix: com.diegofesanto
targets:
  Movies:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Sources]

    info:
      path: Sources/Ui/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"

    preBuildScripts:
      - path: scripts/build_phases/swiftgen.sh
        name: Swiftgen
      - path: scripts/build_phases/swiftymocky.sh
        name: Swifty Mocky

    scheme:
      testTargets:
        - MoviesTests
      gatherCoverageData: true

    dependencies:
      - carthage: RealmSwift
      - carthage: Realm
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: TinyConstraints

  MoviesTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]

    dependencies:
      - target: Movies
      - carthage: SwiftyMocky
      - carthage: RxSwift
   